"""Canonical-resume provenance tests for the frozen M092 criterion runner."""
from __future__ import annotations

import pytest

import metamorphosis.m092_criterion_search as criterion
from metamorphosis.m092_certificate_verifier import COUNTDOWN_POSTCONDITION
from scripts.run_m092_criterion_search import _verified_resume_state


def _refresh_state_digest(value: dict[str, object]) -> None:
    payload = dict(value)
    payload.pop("state_digest", None)
    value["state_digest"] = criterion._sha256(payload)


def test_canonical_resume_replays_a_valid_saved_prefix_exactly() -> None:
    state = criterion.advance_search(
        criterion.CriterionSearchState.fresh(COUNTDOWN_POSTCONDITION),
        COUNTDOWN_POSTCONDITION,
        program_limit=1,
    )

    restored = _verified_resume_state(state.to_dict(), COUNTDOWN_POSTCONDITION)

    assert restored.to_dict() == state.to_dict()


def test_canonical_resume_rejects_a_rehashed_but_semantically_forged_state() -> None:
    forged = criterion.CriterionSearchState.fresh(COUNTDOWN_POSTCONDITION).to_dict()

    # The embedded SHA-256 is an integrity checksum, not a signature. Demonstrate the exact threat:
    # a rewritten counter plus a freshly computed checksum still passes the generic state loader.
    forged["certificate_policy_attempts"] = 1
    forged["criterion_event_chain_digest"] = "1" * 64
    _refresh_state_digest(forged)

    criterion.CriterionSearchState.from_dict(forged)

    with pytest.raises(SystemExit, match="does not match deterministic replay"):
        _verified_resume_state(forged, COUNTDOWN_POSTCONDITION)


def test_canonical_resume_replay_binds_the_complete_serialized_state() -> None:
    state = criterion.advance_search(
        criterion.CriterionSearchState.fresh(COUNTDOWN_POSTCONDITION),
        COUNTDOWN_POSTCONDITION,
        program_limit=1,
    ).to_dict()

    state["criterion_event_chain_digest"] = "2" * 64
    _refresh_state_digest(state)

    # The generic loader accepts a syntactically valid, re-hashed chain value. The canonical runner
    # must reject it because replay reconstructs the unique chain generated by the frozen search.
    criterion.CriterionSearchState.from_dict(state)
    with pytest.raises(SystemExit, match="does not match deterministic replay"):
        _verified_resume_state(state, COUNTDOWN_POSTCONDITION)
