"""Counterexamples for journal authority and migration identity.

A digest chain is evidence about immutable records only if untrusted lineage code cannot also mutate
the records being digested. Likewise, carrying a lineage requires identity and provenance rather than
counts or labels that can be supplied by the migration caller.
"""
from __future__ import annotations

from genesis import development_bodies as bodies
from genesis import journal as jr
from genesis import migration as mg
from genesis import state as st
from genesis import trust_root as tr
from genesis.loop import Genesis


def _seed_state(*, acquisitions=()):
    return st.create_state(
        body_digest="b0",
        components=[
            {
                "name": "operator_table",
                "origin": "seed",
                "certificate": None,
                "provenance": tr.provenance("host_written", produced_by="seed"),
            }
        ],
        vocabulary=[{"name": "axis_progress", "origin": "seed", "certificate": None}],
        acquisitions=list(acquisitions),
    )


def test_append_does_not_return_authority_over_the_stored_history():
    journal = jr.Journal()
    returned = journal.append("observation", 0, {"nested": {"value": 1}})
    returned["payload"]["nested"]["value"] = 99
    assert journal.entries()[0]["payload"]["nested"]["value"] == 1


def test_iteration_does_not_return_authority_over_the_stored_history():
    journal = jr.Journal()
    journal.append("observation", 0, {"nested": {"value": 1}})
    exposed = next(iter(journal))
    exposed["payload"]["nested"]["value"] = 99
    assert journal.entries()[0]["payload"]["nested"]["value"] == 1


def test_entries_returns_a_deep_snapshot_not_shared_nested_payloads():
    journal = jr.Journal()
    journal.append("observation", 0, {"nested": {"value": 1}})
    snapshot = journal.entries()
    snapshot[0]["payload"]["nested"]["value"] = 99
    assert journal.entries()[0]["payload"]["nested"]["value"] == 1


def test_carried_intact_detects_loss_of_one_duplicate_record():
    repeated = {
        "name": "same-acquisition",
        "provenance": tr.provenance("lineage_owned", produced_by="lineage"),
    }
    departing = _seed_state(acquisitions=[repeated, repeated])
    arrived = _seed_state(acquisitions=[repeated])
    result = mg.carried_intact(departing, arrived)
    assert result["intact"] is False
    assert result["carried"]["acquisitions"]["missing"] == 1


def test_migration_does_not_call_a_host_supplied_translation_lineage_owned():
    genesis = Genesis(
        state=_seed_state(),
        body_factory=bodies.parent_body,
        budget=tr.Budget(limits={"generations": 2}),
        isolation=tr.Isolation(),
        grade=bodies.grade,
    )
    substrate = mg.Substrate(name="host-translated", operations={"read": lambda task: task})
    substrate.probe("read")

    # This callable is visibly supplied by the host-side test, not generated by the lineage.
    def host_translation(_state, operations):
        operations["read"]({"task_id": "translation-probe"})
        return bodies.parent_body

    mg.migrate(
        genesis,
        substrate,
        host_translation,
        used_operations=["read"],
        tasks=None,
    )
    provenance = genesis.journal.of_kind("migration")[-1]["payload"]["provenance"]
    assert provenance["class"] != "lineage_owned"
