from __future__ import annotations

from pathlib import Path

from check_attribution_policy import (
    audit_commit_records,
    audit_pull_request_payload,
)


def _record(**overrides: str) -> dict[str, str]:
    row = {
        "commit": "abc123",
        "author_name": "Anthony Mets",
        "author_email": "110968830+mjodheim@users.noreply.github.com",
        "committer_name": "Anthony Mets",
        "committer_email": "110968830+mjodheim@users.noreply.github.com",
        "body": "Add a bounded experiment",
    }
    row.update(overrides)
    return row


def test_human_commit_identity_passes():
    assert audit_commit_records([_record()]) == []


def test_service_author_is_rejected():
    problems = audit_commit_records([_record(author_name="release[bot]")])
    assert problems == [
        "abc123: author_name contains blocked attribution '[bot]'",
        "abc123: author is not a registered human identity",
    ]


def test_unregistered_plain_identity_is_rejected():
    problems = audit_commit_records(
        [_record(author_name="Build Service", author_email="build@example.invalid")]
    )
    assert problems == ["abc123: author is not a registered human identity"]


def test_generated_coauthor_trailer_is_rejected():
    problems = audit_commit_records(
        [_record(body="Change\n\nCo-authored-by: tool[bot] <tool@example.invalid>")]
    )
    assert problems == [
        "abc123: co-author trailer contains blocked attribution '[bot]'",
        "abc123: co-author is not a registered human identity",
    ]


def test_registered_coauthor_trailer_passes():
    problems = audit_commit_records(
        [
            _record(
                body=(
                    "Change\n\nCo-authored-by: Anthony Mets "
                    "<110968830+mjodheim@users.noreply.github.com>"
                )
            )
        ]
    )
    assert problems == []


def test_neutral_pull_request_metadata_passes():
    payload = {
        "pull_request": {
            "title": "Add seeded clade evaluation",
            "body": "Tests a pre-written exploration intervention.",
            "head": {"ref": "research/m027-seeded-clade"},
            "user": {"login": "mjodheim"},
        }
    }
    assert audit_pull_request_payload(payload) == []


def test_unregistered_pull_request_author_is_rejected():
    payload = {
        "pull_request": {
            "title": "Add bounded evaluation",
            "body": "Tests a pre-written intervention.",
            "head": {"ref": "research/change"},
            "user": {"login": "external-service"},
        }
    }
    assert audit_pull_request_payload(payload) == [
        "pull request author is not a registered human identity"
    ]


def test_tool_credit_in_pull_request_metadata_is_rejected():
    payload = {
        "pull_request": {
            "title": "Generated by tool",
            "body": "Development assistant: external service",
            "head": {"ref": "research/change"},
            "user": {"login": "mjodheim"},
        }
    }
    assert audit_pull_request_payload(payload) == [
        "pull request title contains tool-credit language",
        "pull request body contains tool-credit language",
    ]


def test_generic_tool_credit_in_commit_message_is_rejected():
    problems = audit_commit_records([_record(body="Generated with a development tool")])
    assert problems == ["abc123: commit message contains tool-credit language"]


def test_workflow_runs_the_policy_from_the_trusted_base_revision():
    workflow = (
        Path(__file__).parents[1] / ".github" / "workflows" / "attribution-policy.yml"
    ).read_text(encoding="utf-8")
    assert "pull_request_target:" in workflow
    assert "ref: ${{ github.event.pull_request.base.sha }}" in workflow
    assert "Fetch the proposed commit without checking it out" in workflow
    assert "Check commit and pull-request attribution from trusted code" in workflow
