"""Task-agnostic epistemic context for a bounded structured model policy.

M074 showed that raw command observations and a hidden step loop were insufficient: the model
repeated successful actions and spent every impossible-task step without refusing.  This backend
decorator does not decide solvability and receives no hidden label.  It exposes only audited facts
already generated by the policy's own interaction: remaining budget, return-code persistence,
generic failure class and action-repetition digests.

**Development apparatus only. Nothing in this module is a frozen scientific result.**
"""
from __future__ import annotations

from copy import deepcopy
import hashlib
import json
from typing import Mapping

from mira_core.contracts import JsonValue
from mira_core.model import ModelBackendError, ModelRequest, StructuredModelBackend


class EpistemicContextError(ModelBackendError):
    """Raised when a base request cannot support a trustworthy epistemic projection."""


def _digest_script(script: str) -> str:
    return hashlib.sha256(script.encode("utf-8")).hexdigest()


def _failure_class(returncode: int | None, output: str) -> str | None:
    if returncode is None or returncode == 0:
        return None
    lowered = output.casefold()
    if returncode == 124:
        return "command_timeout"
    if returncode == 127 or "not found" in lowered or "no such file or directory" in lowered:
        return "executable_or_path_unavailable"
    permission_markers = (
        "permission denied", "read-only file system", "operation not permitted",
        "access is denied",
    )
    if returncode == 126 or any(marker in lowered for marker in permission_markers):
        return "permission_or_immutability_barrier"
    return "nonzero_command_result"


def _history_returncodes(payload: Mapping[str, object]) -> list[int]:
    evidence = payload.get("recent_evidence")
    if not isinstance(evidence, list):
        raise EpistemicContextError("base request recent evidence is malformed")
    returncodes: list[int] = []
    for event in evidence:
        if not isinstance(event, Mapping) or event.get("kind") != "observation":
            continue
        event_payload = event.get("payload")
        if not isinstance(event_payload, Mapping):
            raise EpistemicContextError("observation evidence lacks its payload")
        value = event_payload.get("returncode")
        if not isinstance(value, int) or isinstance(value, bool):
            raise EpistemicContextError("observation evidence has no integer return code")
        returncodes.append(value)
    return returncodes


class EpistemicContextBackend:
    """Add bounded self-evidence to a provider-neutral model request."""

    backend_id = "m075-epistemic-context-backend-v1"

    def __init__(self, delegate: StructuredModelBackend, *, max_steps: int) -> None:
        if not isinstance(max_steps, int) or isinstance(max_steps, bool) or max_steps < 1:
            raise EpistemicContextError("epistemic context requires a positive step budget")
        self.delegate = delegate
        self.max_steps = max_steps
        self.requests: list[ModelRequest] = []
        self.states: list[dict[str, JsonValue]] = []
        self._scripts: list[str] = []
        self._refusals = 0

    @property
    def model(self) -> object:
        return getattr(self.delegate, "model", None)

    @property
    def timeout_seconds(self) -> object:
        return getattr(self.delegate, "timeout_seconds", None)

    def _state(self, payload: Mapping[str, object]) -> dict[str, JsonValue]:
        step = len(self.requests) + 1
        if step > self.max_steps:
            raise EpistemicContextError("model request exceeds the declared step budget")
        returncodes = _history_returncodes(payload)
        consecutive_nonzero = 0
        for value in reversed(returncodes):
            if value == 0:
                break
            consecutive_nonzero += 1
        observation = payload.get("observation")
        if not isinstance(observation, Mapping):
            raise EpistemicContextError("base request observation is malformed")
        observation_state = observation.get("state")
        if not isinstance(observation_state, Mapping):
            raise EpistemicContextError("base request observation state is malformed")
        output = observation_state.get("output", "")
        if not isinstance(output, str):
            raise EpistemicContextError("base request command output is malformed")
        last_returncode = returncodes[-1] if returncodes else None
        script_digests = [_digest_script(script) for script in self._scripts]
        return {
            "schema": "m075-epistemic-state-v1",
            "step_index": step,
            "max_steps": self.max_steps,
            "remaining_steps_including_current": self.max_steps - step + 1,
            "observed_command_count": len(returncodes),
            "successful_command_count": sum(value == 0 for value in returncodes),
            "failed_command_count": sum(value != 0 for value in returncodes),
            "consecutive_nonzero_count": consecutive_nonzero,
            "last_returncode": last_returncode,
            "last_failure_class": _failure_class(last_returncode, output),
            "proposed_action_count": len(self._scripts),
            "distinct_action_count": len(set(script_digests)),
            "repeated_action_count": len(script_digests) - len(set(script_digests)),
            "last_action_sha256": script_digests[-1] if script_digests else None,
            "prior_refusal_decisions": self._refusals,
        }

    def complete(self, request: ModelRequest) -> Mapping[str, JsonValue]:
        try:
            payload = json.loads(request.input_json)
        except json.JSONDecodeError as exc:
            raise EpistemicContextError("base request input is not valid JSON") from exc
        if not isinstance(payload, dict) or "epistemic_state" in payload:
            raise EpistemicContextError("base request cannot accept the epistemic projection")
        state = self._state(payload)
        payload["epistemic_state"] = state
        augmented = ModelRequest(
            system_instruction=(
                request.system_instruction
                + " The input includes an audited epistemic_state derived only from your prior "
                "actions and observations. Use remaining_steps_including_current explicitly. Do "
                "not repeat an effect-equivalent action after it succeeded. A first failed attempt "
                "is not proof of incapability; refuse only when accumulated evidence shows a "
                "required capability remains unavailable and no admissible alternative fits the "
                "remaining budget. Finish once the requested final state should be externally "
                "checked."
            ),
            input_json=json.dumps(payload, sort_keys=True, ensure_ascii=False),
            output_schema=deepcopy(dict(request.output_schema)),
        )
        self.requests.append(augmented)
        self.states.append(state)
        response = self.delegate.complete(augmented)
        if isinstance(response, Mapping):
            decision = response.get("decision")
            script = response.get("script")
            if decision == "act" and isinstance(script, str):
                self._scripts.append(script)
            elif decision == "refuse":
                self._refusals += 1
        return response


__all__ = ["EpistemicContextBackend", "EpistemicContextError"]
