"""Host-side controller for declarative Genesis evolution intents.

Lineage-owned decision machinery is untrusted. It receives a frozen, inert ``ControllerContext`` and
returns data, while only the host-side executor may spend budget, run probes, mutate state/journal,
migrate, or accept a descendant. The mechanism runs in the same limited subprocess boundary used for
candidate execution, so a read-only value is not mistaken for removal of ambient Python authority.

The current DEVELOPMENT mechanism is still an importable Python symbol rather than a generated policy
artifact. Once admitted, however, its identity is held in lineage state and survives process death and
migration: supplying a different callback is not an implicit policy update. ``ControllerContext`` also
contains bounded inert evidence copied from lineage state/journal, so a later policy can condition a
hypothesis on retained failures instead of seeing only counters.

The DEVELOPMENT world still admits importable body artifacts rather than lineage-generated byte
packages. That code-generation frontier remains explicit and separate from these authority and
continuity boundaries.
"""
from __future__ import annotations

import inspect
import json
from copy import deepcopy
from dataclasses import dataclass, field
from importlib import import_module
from pathlib import Path
from types import MappingProxyType
from typing import Any, Callable, Mapping, Sequence

from genesis import probe
from genesis import state as lineage_state
from genesis.loop import Genesis, LineageContext, Proposal
from genesis.migration import Substrate, discover, metamorphosis_succeeded, migrate
from genesis.sandbox import run_isolated_callable
from genesis.trust_root import (
    Budget,
    BudgetExhausted,
    TrustRootError,
    artifact_digest_of,
    canonical_bytes,
    digest_of,
    provenance,
)

CONTROLLER_SCHEMA = "genesis-controller-run-v1"
WORLD_SCHEMA = "genesis-world-v1"
CONTROLLER_CONTEXT_SCHEMA = "genesis-controller-context-v1"
MECHANISM_TOOL_NAME = "controller_mechanism"
MECHANISM_ROLE = "acquisition_policy"


class ControllerError(RuntimeError):
    """Raised when an intent or mechanism asks for authority it was not admitted to."""


@dataclass(frozen=True)
class Transform:
    name: str
    body: str
    rationale: Mapping[str, Any] = field(default_factory=dict)
    depends_on: str = ""


@dataclass(frozen=True)
class AcquireComponent:
    demand: str
    new_component: str


@dataclass(frozen=True)
class SeparateVocabulary:
    demands: tuple[str, ...]


@dataclass(frozen=True)
class Migrate:
    substrate: str
    probe_for: tuple[str, ...]
    translation: str
    used_operations: tuple[str, ...]


@dataclass(frozen=True)
class SearchTransform:
    """Ask the runtime to *construct* candidate bodies rather than name one it already holds.

    `Transform` selects from `World.artifacts`, so every body it can propose existed before the
    lineage started. This is the intent that does not: the executor enumerates programs over the
    admitted operation grammar under the declared bound, charges each to the lineage's budget, and
    puts them through the same isolated evaluator and the same trust root as any other candidate.

    The policy chooses **why and where** to search. It does not construct the candidates, does not
    see the grader or the withheld answers, and does not decide acceptance — the separation that
    makes an adopted descendant evidence rather than a preference.
    """

    name: str
    max_candidates: int = 8
    max_nodes: int = 3
    operations: tuple[str, ...] = ()
    depends_on: str = ""
    rationale: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class AdoptPolicy:
    """Propose replacing the lineage's own acquisition machinery, on evidence.

    This is the transaction `_bind_mechanism` refuses to perform implicitly. The incumbent policy
    and the candidate are each given a fork of the *same* committed lineage, the same world and the
    same allowance; each drives its fork; and the descendants they produce are compared by the
    unchanged trust root under the admitted contract.

    Neither policy grades anything. The measure stays where it has always been — outside both of
    them — which is what makes an adopted policy a finding about what it produced rather than a
    preference it expressed about itself.
    """

    candidate: str
    steps: int = 2
    rationale: Mapping[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Stop:
    reason: str = ""


@dataclass(frozen=True)
class ControllerContext:
    """The inert lineage view supplied to the isolated decision mechanism.

    It deliberately contains evidence *about* the lineage, not handles to the lineage. There is no
    grader, trust-root service, live journal, mutable state mapping, substrate callable or budget
    object in this value.
    """

    schema: str
    state_digest: str
    generation: int
    components: tuple[str, ...]
    vocabulary: tuple[str, ...]
    acquisitions: tuple[str, ...]
    observations: int
    evidence: tuple[Mapping[str, Any], ...]
    budget_remaining: Mapping[str, int]
    evaluated_task_sets: tuple[str, ...]
    body_artifact_digest: str
    mechanism_artifact_digest: str


@dataclass(frozen=True)
class World:
    schema: str
    tasks: tuple[Mapping[str, Any], ...]
    demands: Mapping[str, Sequence[Mapping[str, Any]]]
    substrates: Mapping[str, Substrate]
    probe_registry: str
    component_operations: Mapping[str, Sequence[str]]
    artifacts: Mapping[str, str]
    grade: Callable[[Mapping[str, Any], Any], str]
    #: Acquisition policies the host admits as *candidates*. Naming one here is not adopting it:
    #: which policy the lineage runs under changes only through the evidence-backed transaction
    #: below. The host says what exists; the lineage's own evidence says what it becomes.
    policies: Mapping[str, str] = field(default_factory=dict)

    def resolve_policy(self, reference: str) -> Callable[..., Any]:
        """Resolve an admitted candidate policy. Resolution is not adoption."""
        target = self.policies.get(str(reference))
        if target is None:
            raise ControllerError(
                "the lineage named policy %r, which this world does not admit" % reference
            )
        return self._import(str(target), reference)

    def _import(self, target: str, reference: str) -> Callable[..., Any]:
        module_name, separator, qualname = target.partition(":")
        if not module_name or not separator or not qualname:
            raise ControllerError("artifact %r has no importable module:symbol target" % reference)
        resolved: Any = import_module(module_name)
        for part in qualname.split("."):
            resolved = getattr(resolved, part)
        if not callable(resolved):
            raise ControllerError("artifact %r does not resolve to something runnable" % reference)
        return resolved

    def resolve(self, reference: str) -> Callable[[], Any]:
        target = self.artifacts.get(str(reference))
        if target is None:
            raise ControllerError(
                "the lineage named artifact %r, which this world does not contain" % reference
            )
        module_name, separator, qualname = str(target).partition(":")
        if not module_name or not separator or not qualname:
            raise ControllerError("artifact %r has no importable module:symbol target" % reference)
        resolved: Any = import_module(module_name)
        for part in qualname.split("."):
            resolved = getattr(resolved, part)
        if not callable(resolved):
            raise ControllerError("artifact %r does not resolve to something runnable" % reference)
        return resolved

    def record(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "tasks": len(self.tasks),
            "demands": sorted(self.demands),
            "substrates": sorted(self.substrates),
            "artifacts": sorted(self.artifacts),
            "policies": sorted(self.policies),
        }


def world(
    *, tasks, demands, substrates, probe_registry, component_operations, artifacts, grade,
    policies=None,
) -> World:
    return World(
        schema=WORLD_SCHEMA,
        tasks=tuple(dict(task) for task in tasks),
        demands={str(name): [dict(task) for task in value] for name, value in demands.items()},
        substrates=dict(substrates),
        probe_registry=str(probe_registry),
        component_operations={str(k): list(v) for k, v in component_operations.items()},
        artifacts={str(k): str(v) for k, v in artifacts.items()},
        grade=grade,
        policies={str(k): str(v) for k, v in (policies or {}).items()},
    )


LINEAGE = provenance("lineage_owned", produced_by="lineage mechanism")
MECHANISM_ADMISSION = provenance(
    "host_written",
    produced_by="Genesis controller admission",
    detail="initial decision mechanism becomes persistent lineage-held machinery",
)


def _transform(genesis: Genesis, here: World, intent: Transform) -> dict[str, Any]:
    proposal = Proposal(
        name=intent.name,
        body_factory=here.resolve(intent.body),
        provenance=LINEAGE,
        rationale=dict(intent.rationale),
        depends_on=intent.depends_on,
    )
    return genesis.cycle(here.tasks, lambda _context, _tasks: proposal)


def _search_transform(genesis: Genesis, here: World, intent: SearchTransform) -> dict[str, Any]:
    """Enumerate candidate programs, evaluate them, and let the trust root decide.

    The enumeration is deterministic and exhaustive over a tiny grammar. Search sophistication is
    not the claim and saying so is the point: what is new is that the body which gets adopted was
    *built here*, from evidence, rather than installed by the host before the run began.
    """
    from genesis import program as program_language

    alphabet = list(intent.operations) or sorted(
        {name for names in here.component_operations.values() for name in names}
    )
    if not alphabet:
        raise ControllerError(
            "a search needs an operation alphabet; this world admits none for the held components"
        )
    budget_dimension = "probes" if "probes" in genesis.budget.limits else "generations"

    considered: list[dict[str, Any]] = []
    adopted: Mapping[str, Any] | None = None
    exhausted = True
    for candidate in program_language.enumerate_programs(
        alphabet,
        registry_reference=here.probe_registry,
        max_nodes=max(1, int(intent.max_nodes)),
    ):
        if len(considered) >= max(1, int(intent.max_candidates)):
            # Stopping at the declared bound rather than when something works: a search that ran
            # past its budget because it had not succeeded yet is not a bounded search.
            exhausted = False
            break
        try:
            genesis.budget.spend(budget_dimension)
        except BudgetExhausted:
            exhausted = False
            break
        artifact = program_language.program_artifact(candidate)
        identity = artifact_digest_of(artifact)
        record = genesis.cycle(
            here.tasks,
            lambda _context, _tasks, _artifact=artifact: Proposal(
                name="%s#%d" % (intent.name, len(considered)),
                body_factory=_artifact,
                provenance=LINEAGE,
                rationale={**dict(intent.rationale), "constructed_by": "controller search"},
                depends_on=intent.depends_on,
            ),
        )
        considered.append(
            {
                "artifact_digest": identity["artifact_digest"],
                "binds_exact_executed_bytes": identity["binds_exact_executed_bytes"],
                "operations": artifact.operations(),
                # The ordered calls as well as the set: two candidates that reach for the same
                # operations in a different order are different programs, and a record that cannot
                # distinguish them is not evidence a later policy could reason over.
                "calls": artifact.calls(),
                "accepted": bool(record.get("accepted")),
                "reason": record.get("reason", ""),
            }
        )
        if record.get("accepted"):
            adopted = record
            break
        if record.get("stopped"):
            exhausted = False
            break

    return {
        "searched": True,
        "candidates_considered": len(considered),
        "candidates": considered,
        "search_space_exhausted": exhausted and adopted is None,
        "accepted": bool(adopted),
        "reason": (adopted or {}).get("reason", "")
        if adopted
        else "no constructed candidate improved on the parent",
        "adopted_artifact_digest": artifact_digest_of(genesis.body_factory)["artifact_digest"]
        if adopted
        else "",
        "outcomes_are_self_reported": (adopted or {}).get("outcomes_are_self_reported"),
        "causal_dependency": (adopted or {}).get("causal_dependency"),
        "body_was_constructed_not_selected": True,
        "stopped": bool((adopted or {}).get("stopped", False)),
    }


def _fork(genesis: Genesis) -> Genesis:
    """A throwaway lineage that starts where this one is, so a trial changes nothing real.

    Both policies must be judged from the *same* starting point or the comparison measures which one
    went first. The fork carries the committed state, the journal and an allowance equal to what
    remains — not the live objects, so nothing a trial does reaches the lineage it was forked from.
    """
    from genesis.journal import Journal

    return Genesis(
        state=deepcopy(dict(genesis.state)),
        body_factory=genesis.body_factory,
        budget=Budget(limits=dict(genesis.budget.limits), spent=dict(genesis.budget.spent)),
        isolation=genesis.isolation,
        journal=Journal(deepcopy(genesis.journal.entries())),
        admitted_isolation=genesis.admitted_isolation,
        admitted_source_sha256=genesis.admitted_source_sha256,
        grade=genesis.grade,
        allow_self_reported_outcomes=genesis.allow_self_reported_outcomes,
    )


def _rebind_mechanism(genesis: Genesis, artifact: Mapping[str, Any], *, why: str) -> None:
    """Replace the bound decision machinery. Only a trial fork or an adopted update may call this."""
    admitted = _canonical_record(artifact)
    tools = [
        tool
        for tool in genesis.state["tools"]
        if not (tool.get("name") == MECHANISM_TOOL_NAME and tool.get("role") == MECHANISM_ROLE)
    ]
    genesis.state = lineage_state.create_state(
        body_digest=genesis.state["body_digest"],
        components=genesis.state["components"],
        vocabulary=genesis.state["vocabulary"],
        tools=tools
        + [
            {
                "name": MECHANISM_TOOL_NAME,
                "role": MECHANISM_ROLE,
                "artifact": admitted,
                "provenance": LINEAGE,
            }
        ],
        acquisitions=genesis.state["acquisitions"],
        observations=genesis.state["observations"],
        generation=genesis.state["generation"],
    )
    genesis.journal.append(
        "observation",
        genesis.state["generation"],
        {
            "arm": "controller_mechanism_update",
            "artifact_digest": admitted.get("artifact_digest", ""),
            "why": why,
            "new_state_digest": genesis.state["state_digest"],
        },
    )


def _trial(genesis: Genesis, here: World, policy: Any, steps: int) -> dict[str, Any]:
    """Let one policy drive a fork, and report what its descendants can do.

    The outcomes come from running the fork's final body over the world's tasks through the same
    isolated evaluator every other candidate goes through. Nothing the policy said about itself is
    read.
    """
    from genesis.sandbox import run_candidate

    fork = _fork(genesis)
    artifact = artifact_digest_of(_canonical_mechanism(policy))
    _rebind_mechanism(fork, artifact, why="meta-evaluation trial")
    # A trial may not change machinery. Without this a policy that asks for its own replacement
    # recurses without bound — each trial running the policy that starts another trial — and, worse,
    # the thing being measured would change in the middle of measuring it.
    record = run(fork, here, policy, max_steps=steps, allow_policy_update=False)
    measured = run_candidate(
        fork.body_factory,
        here.tasks,
        fork.isolation,
        admitted_isolation=fork.admitted_isolation,
        grade=fork.grade,
    )
    if not measured["completed"]:
        raise ControllerError(
            "a policy trial could not be measured, so neither policy can be preferred: %s"
            % measured.get("reason", "")
        )
    return {
        "policy_artifact": artifact,
        "outcomes": measured["outcomes"],
        "acquisitions": len(fork.state["acquisitions"]),
        "body_artifact_digest": artifact_digest_of(fork.body_factory)["artifact_digest"],
        "steps": [step.get("intent") for step in record["steps"]],
    }


def _adopt_policy(genesis: Genesis, here: World, intent: AdoptPolicy) -> dict[str, Any]:
    """Run the matched meta-evaluation and let the trust root decide whether the machinery changes."""
    from genesis.trust_root import decide

    incumbent_artifact = bound_mechanism_artifact(genesis)
    if incumbent_artifact is None:
        raise ControllerError("this lineage carries no acquisition policy to replace")
    candidate_policy = here.resolve_policy(intent.candidate)
    candidate_artifact = artifact_digest_of(_canonical_mechanism(candidate_policy))
    if candidate_artifact["artifact_digest"] == incumbent_artifact.get("artifact_digest"):
        raise ControllerError(
            "the candidate policy is the policy already in force; an update has to be a change"
        )

    incumbent_policy = _resolve_artifact_record(incumbent_artifact)
    steps = max(1, int(intent.steps))
    # Matched: same starting lineage, same world, same allowance, same number of steps.
    incumbent = _trial(genesis, here, incumbent_policy, steps)
    candidate = _trial(genesis, here, candidate_policy, steps)

    verdict = decide(
        parent_outcomes=incumbent["outcomes"],
        candidate_outcomes=candidate["outcomes"],
        budget=genesis.budget,
        isolation=genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
        candidate_provenance=LINEAGE,
        evaluation_contract_record=genesis.evaluation_contract,
    )
    if verdict["accepted"]:
        _rebind_mechanism(
            genesis,
            candidate_artifact,
            why="descendants under the candidate policy beat those under the incumbent",
        )

    return {
        "policy_updated": bool(verdict["accepted"]),
        "candidate": intent.candidate,
        "incumbent_policy_digest": str(incumbent_artifact.get("artifact_digest", "")),
        "candidate_policy_digest": candidate_artifact["artifact_digest"],
        "reason": "; ".join(verdict["rejection_reasons"]),
        "descendants_compared_by": "genesis.trust_root.decide",
        "graded_by_either_policy": False,
        "incumbent_solved": verdict["parent"]["counts"]["solved"],
        "candidate_solved": verdict["candidate"]["counts"]["solved"],
        "lost_solved_tasks": verdict["lost_solved_tasks"],
        "verdict_digest": verdict["verdict_digest"],
        "trial_steps": {"incumbent": incumbent["steps"], "candidate": candidate["steps"]},
    }


def _acquire_component(genesis: Genesis, here: World, intent: AcquireComponent) -> dict[str, Any]:
    demand = here.demands.get(intent.demand)
    if demand is None:
        raise ControllerError("no demand named %r in this world" % intent.demand)
    found = probe.diagnose_by_experiment(
        genesis.state,
        registry_reference=here.probe_registry,
        component_operations=here.component_operations,
        tasks=demand,
        isolation=genesis.isolation,
        budget=genesis.budget,
    )
    if not found["licenses_naming_a_new_component"]:
        genesis.journal.append(
            "diagnosis",
            genesis.state["generation"],
            {"proposed": False, "detail": found["why_not"], "diagnosis_digest": digest_of(found)},
        )
        return {"acquired": False, "why_not": found["why_not"], "diagnosis": found}
    certificate = probe.certificate_from_experiment(found, new_component=intent.new_component)
    genesis.adopt_component(certificate, provenance=LINEAGE)
    return {
        "acquired": True,
        "component": intent.new_component,
        "probe_is_experimental_not_an_oracle": True,
        "registry_exhausted": found["registry_exhausted"],
        "reachable_with_wider_operations": found["reachable_with_wider_operations"],
        "composition_the_lineage_found": found["resolving_composition"]["operations"],
        "compositions_run": sum(record["attempts"] for record in found["probes"]),
        "probed": [record["component"] for record in found["probes"]],
        "registry_after": lineage_state.component_names(genesis.state),
    }


def _separate_vocabulary(genesis: Genesis, here: World, intent: SeparateVocabulary) -> dict[str, Any]:
    demands = []
    for name in intent.demands:
        demand = here.demands.get(name)
        if demand is None:
            raise ControllerError("no demand named %r in this world" % name)
        demands.append(demand)
    pair = probe.find_confusable_pair_by_experiment(
        genesis.state,
        demands,
        registry_reference=here.probe_registry,
        component_operations=here.component_operations,
        isolation=genesis.isolation,
        budget=genesis.budget,
    )
    if pair is None:
        genesis.journal.append(
            "diagnosis",
            genesis.state["generation"],
            {"proposed": False, "detail": "no measured confusable pair"},
        )
        return {"extended": False, "why_not": "no measured confusable pair among these demands"}
    certificate = probe.vocabulary_certificate_from_experiment(genesis.state, pair)
    genesis.adopt_vocabulary(certificate, provenance=LINEAGE)
    return {
        "extended": True,
        "rests_on_a_host_supplied_oracle": False,
        "shared_prior_row": pair["shared_prior_row"],
        "limiting_components": pair["limiting_components"],
        "resolving_operations": [m["resolving_operations"] for m in pair["measurements"]],
        "feature_read_out_of_the_measurements": certificate["new_feature"],
        "vocabulary_after": lineage_state.vocabulary_names(genesis.state),
    }


def _migrate(genesis: Genesis, here: World, intent: Migrate) -> dict[str, Any]:
    substrate = here.substrates.get(intent.substrate)
    if substrate is None:
        raise ControllerError("no substrate named %r in this world" % intent.substrate)
    probing = discover(substrate, list(intent.probe_for), genesis.budget)
    record = migrate(
        genesis,
        substrate,
        here.resolve(intent.translation),
        used_operations=list(intent.used_operations),
        tasks=here.tasks,
        translation_provenance=provenance(
            "host_written",
            produced_by="world-supplied translation artifact",
            detail=str(intent.translation),
        ),
    )
    return {
        "found": probing["found"],
        "missing": probing["missing"],
        "journal_continues": record["journal_continues"],
        "nothing_lost": all(c["missing"] == 0 for c in record["carried"].values()),
        "capability_measured": record["capability"]["measured"],
        "capability_preserved": record["capability"]["preserved"],
        "solved_before_and_after": [
            record["capability"]["solved_before"],
            record["capability"]["solved_after"],
        ],
        "migration": record,
    }


HANDLERS = {
    Transform: _transform,
    SearchTransform: _search_transform,
    AdoptPolicy: _adopt_policy,
    AcquireComponent: _acquire_component,
    SeparateVocabulary: _separate_vocabulary,
    Migrate: _migrate,
}


def _canonical_record(value: Mapping[str, Any]) -> dict[str, Any]:
    """Detach a trusted record into inert JSON data."""
    return json.loads(canonical_bytes(dict(value)).decode("utf-8"))


def bound_mechanism_artifact(genesis: Genesis) -> dict[str, Any] | None:
    """Return the one mechanism artifact held by this lineage, or refuse ambiguity."""
    records = [
        tool
        for tool in genesis.state.get("tools", [])
        if tool.get("name") == MECHANISM_TOOL_NAME and tool.get("role") == MECHANISM_ROLE
    ]
    if not records:
        return None
    if len(records) != 1:
        raise ControllerError("lineage state carries more than one admitted controller mechanism")
    artifact = records[0].get("artifact")
    if not isinstance(artifact, Mapping):
        raise ControllerError("the admitted controller mechanism carries no artifact identity")
    return _canonical_record(artifact)


def _bind_mechanism(genesis: Genesis, artifact: Mapping[str, Any]) -> bool:
    """Admit the initial mechanism once; every later invocation must be exactly the same artifact."""
    admitted = _canonical_record(artifact)
    current = bound_mechanism_artifact(genesis)
    if current is not None:
        if current != admitted:
            raise ControllerError(
                "this lineage is already admitted under controller mechanism %s; replacing it with "
                "%s requires an explicit evidence-backed machinery update"
                % (current.get("artifact_digest"), admitted.get("artifact_digest"))
            )
        return False

    genesis.state = lineage_state.create_state(
        body_digest=genesis.state["body_digest"],
        components=genesis.state["components"],
        vocabulary=genesis.state["vocabulary"],
        tools=genesis.state["tools"]
        + [
            {
                "name": MECHANISM_TOOL_NAME,
                "role": MECHANISM_ROLE,
                "artifact": admitted,
                "provenance": MECHANISM_ADMISSION,
            }
        ],
        acquisitions=genesis.state["acquisitions"],
        observations=genesis.state["observations"],
        generation=genesis.state["generation"],
    )
    genesis.journal.append(
        "observation",
        genesis.state["generation"],
        {
            "arm": "controller_mechanism_admission",
            "artifact_digest": admitted.get("artifact_digest", ""),
            "new_state_digest": genesis.state["state_digest"],
        },
    )
    return True


def _lineage_evidence(genesis: Genesis) -> tuple[Mapping[str, Any], ...]:
    """Bounded inert evidence the policy may inspect without receiving runtime authority."""
    records: list[dict[str, Any]] = []
    for observation in genesis.state.get("observations", []):
        records.append({"kind": "observation", "record": _canonical_record(observation)})
    for acquisition in genesis.state.get("acquisitions", []):
        records.append({"kind": "acquisition", "record": _canonical_record(acquisition)})
    for component in genesis.state.get("components", []):
        certificate = component.get("certificate")
        if isinstance(certificate, Mapping):
            records.append(
                {
                    "kind": "component_certificate",
                    "name": str(component.get("name", "")),
                    "record": _canonical_record(certificate),
                }
            )
    for feature in genesis.state.get("vocabulary", []):
        certificate = feature.get("certificate")
        if isinstance(certificate, Mapping):
            records.append(
                {
                    "kind": "vocabulary_certificate",
                    "name": str(feature.get("name", "")),
                    "record": _canonical_record(certificate),
                }
            )
    # Journal diagnoses and rejections are already inert records and contain no grader handle or
    # withheld task answer. They matter because a failed experiment can be informative without
    # becoming an acquisition in LineageState.
    for kind in ("diagnosis", "candidate_rejected", "migration"):
        for entry in genesis.journal.of_kind(kind):
            records.append(
                {
                    "kind": "journal_%s" % kind,
                    "record": _canonical_record(entry.get("payload") or {}),
                    "entry_digest": str(entry.get("entry_digest", "")),
                }
            )
    return tuple(MappingProxyType(_canonical_record(record)) for record in records)


def _controller_context(genesis: Genesis) -> ControllerContext:
    base = genesis.context()
    mechanism = bound_mechanism_artifact(genesis)
    return ControllerContext(
        schema=CONTROLLER_CONTEXT_SCHEMA,
        state_digest=base.state_digest,
        generation=base.generation,
        components=base.components,
        vocabulary=base.vocabulary,
        acquisitions=base.acquisitions,
        observations=base.observations,
        evidence=_lineage_evidence(genesis),
        budget_remaining=base.budget_remaining,
        evaluated_task_sets=base.evaluated_task_sets,
        body_artifact_digest=base.body_artifact_digest,
        mechanism_artifact_digest=""
        if mechanism is None
        else str(mechanism.get("artifact_digest", "")),
    )


def _context_record(context: ControllerContext) -> dict[str, Any]:
    return {
        "schema": context.schema,
        "state_digest": context.state_digest,
        "generation": context.generation,
        "components": list(context.components),
        "vocabulary": list(context.vocabulary),
        "acquisitions": list(context.acquisitions),
        "observations": context.observations,
        "evidence": [dict(record) for record in context.evidence],
        "budget_remaining": dict(context.budget_remaining),
        "evaluated_task_sets": list(context.evaluated_task_sets),
        "body_artifact_digest": context.body_artifact_digest,
        "mechanism_artifact_digest": context.mechanism_artifact_digest,
    }


def _context_from_record(record: Mapping[str, Any]) -> ControllerContext:
    evidence = tuple(
        MappingProxyType(_canonical_record(value))
        for value in record.get("evidence") or []
        if isinstance(value, Mapping)
    )
    return ControllerContext(
        schema=str(record["schema"]),
        state_digest=str(record["state_digest"]),
        generation=int(record["generation"]),
        components=tuple(str(v) for v in record.get("components") or []),
        vocabulary=tuple(str(v) for v in record.get("vocabulary") or []),
        acquisitions=tuple(str(v) for v in record.get("acquisitions") or []),
        observations=int(record.get("observations", 0)),
        evidence=evidence,
        budget_remaining=MappingProxyType(
            {str(k): int(v) for k, v in (record.get("budget_remaining") or {}).items()}
        ),
        evaluated_task_sets=tuple(str(v) for v in record.get("evaluated_task_sets") or []),
        body_artifact_digest=str(record["body_artifact_digest"]),
        mechanism_artifact_digest=str(record.get("mechanism_artifact_digest") or ""),
    )


def _intent_record(intent: Any) -> dict[str, Any]:
    if intent is None:
        return {"type": "none"}
    if isinstance(intent, Transform):
        return {
            "type": "Transform",
            "name": intent.name,
            "body": intent.body,
            "rationale": dict(intent.rationale),
            "depends_on": intent.depends_on,
        }
    if isinstance(intent, SearchTransform):
        return {
            "type": "SearchTransform",
            "name": intent.name,
            "max_candidates": int(intent.max_candidates),
            "max_nodes": int(intent.max_nodes),
            "operations": list(intent.operations),
            "depends_on": intent.depends_on,
            "rationale": dict(intent.rationale),
        }
    if isinstance(intent, AdoptPolicy):
        return {
            "type": "AdoptPolicy",
            "candidate": intent.candidate,
            "steps": int(intent.steps),
            "rationale": dict(intent.rationale),
        }
    if isinstance(intent, AcquireComponent):
        return {
            "type": "AcquireComponent",
            "demand": intent.demand,
            "new_component": intent.new_component,
        }
    if isinstance(intent, SeparateVocabulary):
        return {"type": "SeparateVocabulary", "demands": list(intent.demands)}
    if isinstance(intent, Migrate):
        return {
            "type": "Migrate",
            "substrate": intent.substrate,
            "probe_for": list(intent.probe_for),
            "translation": intent.translation,
            "used_operations": list(intent.used_operations),
        }
    if isinstance(intent, Stop):
        return {"type": "Stop", "reason": intent.reason}
    raise ControllerError("the lineage returned %r, which is not an intent" % (intent,))


def _intent_from_record(record: Mapping[str, Any]) -> Any:
    kind = str(record.get("type") or "")
    if kind == "none":
        return None
    if kind == "Transform":
        return Transform(
            name=str(record["name"]),
            body=str(record["body"]),
            rationale=dict(record.get("rationale") or {}),
            depends_on=str(record.get("depends_on") or ""),
        )
    if kind == "SearchTransform":
        return SearchTransform(
            name=str(record["name"]),
            max_candidates=int(record.get("max_candidates", 8)),
            max_nodes=int(record.get("max_nodes", 3)),
            operations=tuple(str(v) for v in record.get("operations") or []),
            depends_on=str(record.get("depends_on") or ""),
            rationale=dict(record.get("rationale") or {}),
        )
    if kind == "AdoptPolicy":
        return AdoptPolicy(
            candidate=str(record["candidate"]),
            steps=int(record.get("steps", 2)),
            rationale=dict(record.get("rationale") or {}),
        )
    if kind == "AcquireComponent":
        return AcquireComponent(
            demand=str(record["demand"]), new_component=str(record["new_component"])
        )
    if kind == "SeparateVocabulary":
        return SeparateVocabulary(demands=tuple(str(v) for v in record.get("demands") or []))
    if kind == "Migrate":
        return Migrate(
            substrate=str(record["substrate"]),
            probe_for=tuple(str(v) for v in record.get("probe_for") or []),
            translation=str(record["translation"]),
            used_operations=tuple(str(v) for v in record.get("used_operations") or []),
        )
    if kind == "Stop":
        return Stop(reason=str(record.get("reason") or ""))
    raise ControllerError("isolated mechanism returned an unrecognised intent record %r" % kind)


def _resolve_artifact_record(record: Mapping[str, Any]) -> Callable[..., Any]:
    if record.get("kind") != "importable_symbol":
        raise ControllerError("controller mechanisms must be importable symbols in DEVELOPMENT")
    module_name = str(record.get("module") or "")
    qualname = str(record.get("qualname") or "")
    target: Any = import_module(module_name)
    for part in qualname.split("."):
        target = getattr(target, part)
    rebuilt = artifact_digest_of(target)
    if rebuilt["artifact_digest"] != record.get("artifact_digest"):
        raise ControllerError("controller mechanism no longer matches its admitted artifact")
    return target


def _isolated_mechanism_entry(payload: Mapping[str, Any]) -> dict[str, Any]:
    mechanism = _resolve_artifact_record(payload.get("mechanism") or {})
    context = _context_from_record(payload.get("context") or {})
    return _intent_record(mechanism(context))


def _canonical_mechanism(
    mechanism: Callable[[ControllerContext], Any],
) -> Callable[[ControllerContext], Any]:
    if getattr(mechanism, "__module__", "") != "__main__":
        return mechanism
    source = inspect.getsourcefile(mechanism)
    if not source:
        raise ControllerError(
            "a __main__ mechanism has no source path from which to derive an importable identity"
        )
    path = Path(source).resolve()
    root = Path.cwd().resolve()
    try:
        relative = path.relative_to(root).with_suffix("")
    except ValueError as problem:
        raise ControllerError("a __main__ mechanism outside the repository cannot be admitted") from problem
    module_name = ".".join(relative.parts)
    resolved: Any = import_module(module_name)
    for part in str(getattr(mechanism, "__qualname__", "")).split("."):
        resolved = getattr(resolved, part)
    return resolved


def _admit_mechanism(
    genesis: Genesis, mechanism: Callable[[ControllerContext], Any]
) -> tuple[Callable[[ControllerContext], Any], dict[str, Any], bool]:
    admitted = _canonical_mechanism(mechanism)
    artifact = artifact_digest_of(admitted)
    if artifact.get("kind") != "importable_symbol":
        raise ControllerError("controller mechanisms must be content-addressed importable symbols")
    newly_bound = _bind_mechanism(genesis, artifact)
    return admitted, artifact, newly_bound


def _invoke_admitted_mechanism(
    genesis: Genesis,
    mechanism: Callable[[ControllerContext], Any],
    artifact: Mapping[str, Any],
) -> Any:
    # Re-check the persisted binding on every step. State can change through migration/acquisition,
    # but changing the decision machinery is not among those implicit transitions.
    current = bound_mechanism_artifact(genesis)
    if current is None or current != _canonical_record(artifact):
        raise ControllerError("the lineage no longer carries the controller mechanism it was admitted under")
    result = run_isolated_callable(
        _isolated_mechanism_entry,
        {"mechanism": artifact, "context": _context_record(_controller_context(genesis))},
        genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
    )
    if not result["completed"]:
        raise ControllerError(
            "the lineage mechanism did not run under the admitted boundary: %s"
            % (
                result.get("reason")
                or result.get("traceback")
                or "instrument failure"
            )
        )
    value = result.get("value")
    if not isinstance(value, Mapping):
        raise ControllerError("the isolated mechanism returned no intent record")
    return _intent_from_record(value)


def _invoke_mechanism(
    genesis: Genesis, mechanism: Callable[[ControllerContext], Any]
) -> tuple[Any, dict[str, Any]]:
    admitted, artifact, _ = _admit_mechanism(genesis, mechanism)
    return _invoke_admitted_mechanism(genesis, admitted, artifact), artifact


def run(
    genesis: Genesis,
    here: World,
    mechanism: Callable[[ControllerContext], Any],
    *,
    max_steps: int = 32,
    checkpoint_directory: Path | None = None,
    allow_policy_update: bool = True,
) -> dict[str, Any]:
    """Drive one lineage, making each committed controller step durable when storage is supplied.

    The host is allowed to choose *where* checkpoints live. It is not allowed to decide that several
    accepted architectural transitions may remain only in memory: with ``checkpoint_directory`` the
    controller publishes a checkpoint after mechanism admission and after every handled intent before
    asking the lineage for the next one.
    """
    steps: list[dict[str, Any]] = []
    migration_record: Mapping[str, Any] | None = None
    cycles_after_migration: list[Mapping[str, Any]] = []
    admitted, mechanism_artifact, newly_bound = _admit_mechanism(genesis, mechanism)
    checkpoint_path = Path(checkpoint_directory) if checkpoint_directory is not None else None
    admission_checkpoint = ""
    if checkpoint_path is not None and newly_bound:
        admission_checkpoint = genesis.persist(checkpoint_path)["checkpoint"]

    for _ in range(max_steps):
        intent = _invoke_admitted_mechanism(genesis, admitted, mechanism_artifact)
        if intent is None or isinstance(intent, Stop):
            steps.append(
                {"intent": "stop", "reason": getattr(intent, "reason", "no further intent")}
            )
            break
        if isinstance(intent, AdoptPolicy) and not allow_policy_update:
            # Inside a trial this is not an error, it is an answer a trial cannot act on. Asking a
            # policy what it would produce and being told "I would replace myself" says nothing
            # about descendants, and performing it would change the thing under measurement while
            # measuring it — and recurse without bound, since each trial would start another.
            steps.append(
                {
                    "intent": "stop",
                    "reason": "a policy trial may not change the machinery it is measuring",
                    "policy_update_refused_in_trial": True,
                }
            )
            break
        handler = HANDLERS.get(type(intent))
        if handler is None:
            raise ControllerError("the lineage returned %r, which is not an intent" % (intent,))
        outcome = handler(genesis, here, intent)
        step = {
            "intent": type(intent).__name__,
            **_summary(intent, outcome),
            "lineage": _lineage(genesis),
        }
        # An adopted policy takes effect from here. Every other transition leaves the machinery
        # alone and the binding check refuses a change it did not license; this one licensed it, on
        # a trust-root verdict about the descendants each policy produced. The loop continuing under
        # the new rule is the point — a changed rule is what produces the next change.
        settled = bound_mechanism_artifact(genesis)
        if settled is not None and settled != _canonical_record(mechanism_artifact):
            mechanism_artifact = settled
            admitted = _resolve_artifact_record(settled)
            step["machinery_in_force_after_this_step"] = settled.get("artifact_digest", "")
        if checkpoint_path is not None:
            step["checkpoint_digest"] = genesis.persist(checkpoint_path)["checkpoint"]
            step["durable_before_next_intent"] = True
        else:
            step["durable_before_next_intent"] = False
        steps.append(step)
        if isinstance(intent, Migrate):
            migration_record = outcome["migration"]
        elif isinstance(intent, Transform) and migration_record is not None:
            cycles_after_migration.append(outcome)
        if outcome.get("stopped"):
            break

    record = {
        "schema": CONTROLLER_SCHEMA,
        "world": here.record(),
        "steps": steps,
        "final_generation": genesis.state["generation"],
        "final_components": lineage_state.component_names(genesis.state),
        "final_vocabulary": lineage_state.vocabulary_names(genesis.state),
        "causal_chain": genesis.causal_chain(),
        "budget": genesis.budget.record(),
        "mechanism_execution_isolated": True,
        "mechanism_artifact_digest": str(mechanism_artifact.get("artifact_digest") or ""),
        "mechanism_identity_persistent": bound_mechanism_artifact(genesis) == _canonical_record(mechanism_artifact),
        "durable_step_persistence": checkpoint_path is not None,
        "mechanism_admission_checkpoint": admission_checkpoint,
    }
    if migration_record is not None:
        record["metamorphosis"] = metamorphosis_succeeded(migration_record, cycles_after_migration)
    record["run_digest"] = digest_of(record)
    return record


def _lineage(genesis: Genesis) -> dict[str, Any]:
    return {
        "generation": genesis.state["generation"],
        "components": lineage_state.component_names(genesis.state),
        "vocabulary": lineage_state.vocabulary_names(genesis.state),
        "acquisitions": len(genesis.state["acquisitions"]),
        "observations_kept": len(genesis.state["observations"]),
        "state_digest": genesis.state["state_digest"],
        "mechanism_artifact_digest": str(
            (bound_mechanism_artifact(genesis) or {}).get("artifact_digest", "")
        ),
    }


def _summary(intent: Any, outcome: Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(intent, Transform):
        return {
            "name": intent.name,
            "accepted": outcome.get("accepted"),
            "reason": outcome.get("reason", ""),
            "outcomes_are_self_reported": outcome.get("outcomes_are_self_reported"),
            "causal_dependency": outcome.get("causal_dependency"),
            "stopped": outcome.get("stopped", False),
        }
    return {k: v for k, v in outcome.items() if k not in ("migration", "diagnosis")}
