"""Host-side controller for declarative Genesis evolution intents.

Lineage-owned mechanism code is untrusted. It receives a frozen ``LineageContext`` and returns data,
but a frozen value alone does not remove Python's ambient authority. The mechanism therefore runs in
the same inert, limited subprocess boundary used for candidate execution; only the host-side executor
may spend budget, run probes, mutate state/journal, migrate, or accept a descendant.

The DEVELOPMENT world still admits importable artifacts rather than lineage-generated byte packages.
That code-generation frontier is explicit and separate from this authority boundary.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from importlib import import_module
import inspect
from pathlib import Path
from types import MappingProxyType
from typing import Any, Callable, Mapping, Sequence

from genesis import probe
from genesis import state as lineage_state
from genesis.loop import Genesis, LineageContext, Proposal
from genesis.migration import Substrate, discover, metamorphosis_succeeded, migrate
from genesis.sandbox import run_isolated_callable
from genesis.trust_root import TrustRootError, artifact_digest_of, digest_of, provenance

CONTROLLER_SCHEMA = "genesis-controller-run-v1"
WORLD_SCHEMA = "genesis-world-v1"


class ControllerError(RuntimeError):
    """Raised when an intent or mechanism asks for authority it was not admitted to."""


@dataclass(frozen=True)
class Transform:
    name: str
    body: str
    rationale: Mapping[str, Any] = field(default_factory=dict)
    depends_on: str = ""


@dataclass(frozen=True)
class AcquireComponent:
    demand: str
    new_component: str


@dataclass(frozen=True)
class SeparateVocabulary:
    demands: tuple[str, ...]


@dataclass(frozen=True)
class Migrate:
    substrate: str
    probe_for: tuple[str, ...]
    translation: str
    used_operations: tuple[str, ...]


@dataclass(frozen=True)
class Stop:
    reason: str = ""


@dataclass(frozen=True)
class World:
    schema: str
    tasks: tuple[Mapping[str, Any], ...]
    demands: Mapping[str, Sequence[Mapping[str, Any]]]
    substrates: Mapping[str, Substrate]
    probe_registry: str
    component_operations: Mapping[str, Sequence[str]]
    artifacts: Mapping[str, str]
    grade: Callable[[Mapping[str, Any], Any], str]

    def resolve(self, reference: str) -> Callable[[], Any]:
        target = self.artifacts.get(str(reference))
        if target is None:
            raise ControllerError("the lineage named artifact %r, which this world does not contain" % reference)
        module_name, separator, qualname = str(target).partition(":")
        if not module_name or not separator or not qualname:
            raise ControllerError("artifact %r has no importable module:symbol target" % reference)
        resolved: Any = import_module(module_name)
        for part in qualname.split("."):
            resolved = getattr(resolved, part)
        if not callable(resolved):
            raise ControllerError("artifact %r does not resolve to something runnable" % reference)
        return resolved

    def record(self) -> dict[str, Any]:
        return {
            "schema": self.schema,
            "tasks": len(self.tasks),
            "demands": sorted(self.demands),
            "substrates": sorted(self.substrates),
            "artifacts": sorted(self.artifacts),
        }


def world(*, tasks, demands, substrates, probe_registry, component_operations, artifacts, grade) -> World:
    return World(
        schema=WORLD_SCHEMA,
        tasks=tuple(dict(task) for task in tasks),
        demands={str(name): [dict(task) for task in value] for name, value in demands.items()},
        substrates=dict(substrates),
        probe_registry=str(probe_registry),
        component_operations={str(k): list(v) for k, v in component_operations.items()},
        artifacts={str(k): str(v) for k, v in artifacts.items()},
        grade=grade,
    )


LINEAGE = provenance("lineage_owned", produced_by="lineage mechanism")


def _transform(genesis: Genesis, here: World, intent: Transform) -> dict[str, Any]:
    proposal = Proposal(
        name=intent.name,
        body_factory=here.resolve(intent.body),
        provenance=LINEAGE,
        rationale=dict(intent.rationale),
        depends_on=intent.depends_on,
    )
    return genesis.cycle(here.tasks, lambda _context, _tasks: proposal)


def _acquire_component(genesis: Genesis, here: World, intent: AcquireComponent) -> dict[str, Any]:
    demand = here.demands.get(intent.demand)
    if demand is None:
        raise ControllerError("no demand named %r in this world" % intent.demand)
    found = probe.diagnose_by_experiment(
        genesis.state,
        registry_reference=here.probe_registry,
        component_operations=here.component_operations,
        tasks=demand,
        isolation=genesis.isolation,
        budget=genesis.budget,
    )
    if not found["licenses_naming_a_new_component"]:
        genesis.journal.append(
            "diagnosis", genesis.state["generation"],
            {"proposed": False, "detail": found["why_not"]},
        )
        return {"acquired": False, "why_not": found["why_not"], "diagnosis": found}
    certificate = probe.certificate_from_experiment(found, new_component=intent.new_component)
    genesis.adopt_component(certificate, provenance=LINEAGE)
    return {
        "acquired": True,
        "component": intent.new_component,
        "probe_is_experimental_not_an_oracle": True,
        "registry_exhausted": found["registry_exhausted"],
        "reachable_with_wider_operations": found["reachable_with_wider_operations"],
        "composition_the_lineage_found": found["resolving_composition"]["operations"],
        "compositions_run": sum(record["attempts"] for record in found["probes"]),
        "probed": [record["component"] for record in found["probes"]],
        "registry_after": lineage_state.component_names(genesis.state),
    }


def _separate_vocabulary(genesis: Genesis, here: World, intent: SeparateVocabulary) -> dict[str, Any]:
    demands = []
    for name in intent.demands:
        demand = here.demands.get(name)
        if demand is None:
            raise ControllerError("no demand named %r in this world" % name)
        demands.append(demand)
    pair = probe.find_confusable_pair_by_experiment(
        genesis.state,
        demands,
        registry_reference=here.probe_registry,
        component_operations=here.component_operations,
        isolation=genesis.isolation,
        budget=genesis.budget,
    )
    if pair is None:
        genesis.journal.append(
            "diagnosis", genesis.state["generation"],
            {"proposed": False, "detail": "no measured confusable pair"},
        )
        return {"extended": False, "why_not": "no measured confusable pair among these demands"}
    certificate = probe.vocabulary_certificate_from_experiment(genesis.state, pair)
    genesis.adopt_vocabulary(certificate, provenance=LINEAGE)
    return {
        "extended": True,
        "rests_on_a_host_supplied_oracle": False,
        "shared_prior_row": pair["shared_prior_row"],
        "limiting_components": pair["limiting_components"],
        "resolving_operations": [m["resolving_operations"] for m in pair["measurements"]],
        "feature_read_out_of_the_measurements": certificate["new_feature"],
        "vocabulary_after": lineage_state.vocabulary_names(genesis.state),
    }


def _migrate(genesis: Genesis, here: World, intent: Migrate) -> dict[str, Any]:
    substrate = here.substrates.get(intent.substrate)
    if substrate is None:
        raise ControllerError("no substrate named %r in this world" % intent.substrate)
    probing = discover(substrate, list(intent.probe_for), genesis.budget)
    record = migrate(
        genesis,
        substrate,
        here.resolve(intent.translation),
        used_operations=list(intent.used_operations),
        tasks=here.tasks,
        translation_provenance=provenance(
            "host_written", produced_by="world-supplied translation artifact", detail=str(intent.translation)
        ),
    )
    return {
        "found": probing["found"],
        "missing": probing["missing"],
        "journal_continues": record["journal_continues"],
        "nothing_lost": all(c["missing"] == 0 for c in record["carried"].values()),
        "capability_measured": record["capability"]["measured"],
        "capability_preserved": record["capability"]["preserved"],
        "solved_before_and_after": [record["capability"]["solved_before"], record["capability"]["solved_after"]],
        "migration": record,
    }


HANDLERS = {Transform: _transform, AcquireComponent: _acquire_component, SeparateVocabulary: _separate_vocabulary, Migrate: _migrate}


def _context_record(context: LineageContext) -> dict[str, Any]:
    return {
        "schema": context.schema,
        "state_digest": context.state_digest,
        "generation": context.generation,
        "components": list(context.components),
        "vocabulary": list(context.vocabulary),
        "acquisitions": list(context.acquisitions),
        "observations": context.observations,
        "budget_remaining": dict(context.budget_remaining),
        "evaluated_task_sets": list(context.evaluated_task_sets),
        "body_artifact_digest": context.body_artifact_digest,
    }


def _context_from_record(record: Mapping[str, Any]) -> LineageContext:
    return LineageContext(
        schema=str(record["schema"]),
        state_digest=str(record["state_digest"]),
        generation=int(record["generation"]),
        components=tuple(str(v) for v in record.get("components") or []),
        vocabulary=tuple(str(v) for v in record.get("vocabulary") or []),
        acquisitions=tuple(str(v) for v in record.get("acquisitions") or []),
        observations=int(record.get("observations", 0)),
        budget_remaining=MappingProxyType({str(k): int(v) for k, v in (record.get("budget_remaining") or {}).items()}),
        evaluated_task_sets=tuple(str(v) for v in record.get("evaluated_task_sets") or []),
        body_artifact_digest=str(record["body_artifact_digest"]),
    )


def _intent_record(intent: Any) -> dict[str, Any]:
    if intent is None:
        return {"type": "none"}
    if isinstance(intent, Transform):
        return {"type": "Transform", "name": intent.name, "body": intent.body, "rationale": dict(intent.rationale), "depends_on": intent.depends_on}
    if isinstance(intent, AcquireComponent):
        return {"type": "AcquireComponent", "demand": intent.demand, "new_component": intent.new_component}
    if isinstance(intent, SeparateVocabulary):
        return {"type": "SeparateVocabulary", "demands": list(intent.demands)}
    if isinstance(intent, Migrate):
        return {"type": "Migrate", "substrate": intent.substrate, "probe_for": list(intent.probe_for), "translation": intent.translation, "used_operations": list(intent.used_operations)}
    if isinstance(intent, Stop):
        return {"type": "Stop", "reason": intent.reason}
    raise ControllerError("the lineage returned %r, which is not an intent" % (intent,))


def _intent_from_record(record: Mapping[str, Any]) -> Any:
    kind = str(record.get("type") or "")
    if kind == "none":
        return None
    if kind == "Transform":
        return Transform(name=str(record["name"]), body=str(record["body"]), rationale=dict(record.get("rationale") or {}), depends_on=str(record.get("depends_on") or ""))
    if kind == "AcquireComponent":
        return AcquireComponent(demand=str(record["demand"]), new_component=str(record["new_component"]))
    if kind == "SeparateVocabulary":
        return SeparateVocabulary(demands=tuple(str(v) for v in record.get("demands") or []))
    if kind == "Migrate":
        return Migrate(substrate=str(record["substrate"]), probe_for=tuple(str(v) for v in record.get("probe_for") or []), translation=str(record["translation"]), used_operations=tuple(str(v) for v in record.get("used_operations") or []))
    if kind == "Stop":
        return Stop(reason=str(record.get("reason") or ""))
    raise ControllerError("isolated mechanism returned an unrecognised intent record %r" % kind)


def _resolve_artifact_record(record: Mapping[str, Any]) -> Callable[..., Any]:
    if record.get("kind") != "importable_symbol":
        raise ControllerError("controller mechanisms must be importable symbols in DEVELOPMENT")
    module_name = str(record.get("module") or "")
    qualname = str(record.get("qualname") or "")
    target: Any = import_module(module_name)
    for part in qualname.split("."):
        target = getattr(target, part)
    rebuilt = artifact_digest_of(target)
    if rebuilt["artifact_digest"] != record.get("artifact_digest"):
        raise ControllerError("controller mechanism no longer matches its admitted artifact")
    return target


def _isolated_mechanism_entry(payload: Mapping[str, Any]) -> dict[str, Any]:
    mechanism = _resolve_artifact_record(payload.get("mechanism") or {})
    context = _context_from_record(payload.get("context") or {})
    return _intent_record(mechanism(context))


def _canonical_mechanism(mechanism: Callable[[LineageContext], Any]) -> Callable[[LineageContext], Any]:
    if getattr(mechanism, "__module__", "") != "__main__":
        return mechanism
    source = inspect.getsourcefile(mechanism)
    if not source:
        raise ControllerError("a __main__ mechanism has no source path from which to derive an importable identity")
    path = Path(source).resolve()
    root = Path.cwd().resolve()
    try:
        relative = path.relative_to(root).with_suffix("")
    except ValueError as problem:
        raise ControllerError("a __main__ mechanism outside the repository cannot be admitted") from problem
    module_name = ".".join(relative.parts)
    resolved: Any = import_module(module_name)
    for part in str(getattr(mechanism, "__qualname__", "")).split("."):
        resolved = getattr(resolved, part)
    return resolved


def _invoke_mechanism(genesis: Genesis, mechanism: Callable[[LineageContext], Any]) -> tuple[Any, dict[str, Any]]:
    admitted = _canonical_mechanism(mechanism)
    artifact = artifact_digest_of(admitted)
    if artifact.get("kind") != "importable_symbol":
        raise ControllerError("controller mechanisms must be content-addressed importable symbols")
    result = run_isolated_callable(
        _isolated_mechanism_entry,
        {"mechanism": artifact, "context": _context_record(genesis.context())},
        genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
    )
    if not result["completed"]:
        raise ControllerError("the lineage mechanism did not run under the admitted boundary: %s" % (result.get("reason") or result.get("traceback") or "instrument failure"))
    value = result.get("value")
    if not isinstance(value, Mapping):
        raise ControllerError("the isolated mechanism returned no intent record")
    return _intent_from_record(value), artifact


def run(genesis: Genesis, here: World, mechanism: Callable[[LineageContext], Any], *, max_steps: int = 32) -> dict[str, Any]:
    """Drive a lineage while keeping lineage-owned mechanism code outside the evaluator process."""
    steps: list[dict[str, Any]] = []
    migration_record: Mapping[str, Any] | None = None
    cycles_after_migration: list[Mapping[str, Any]] = []
    mechanism_artifact: Mapping[str, Any] | None = None

    for _ in range(max_steps):
        intent, mechanism_artifact = _invoke_mechanism(genesis, mechanism)
        if intent is None or isinstance(intent, Stop):
            steps.append({"intent": "stop", "reason": getattr(intent, "reason", "no further intent")})
            break
        handler = HANDLERS.get(type(intent))
        if handler is None:
            raise ControllerError("the lineage returned %r, which is not an intent" % (intent,))
        outcome = handler(genesis, here, intent)
        steps.append({"intent": type(intent).__name__, **_summary(intent, outcome), "lineage": _lineage(genesis)})
        if isinstance(intent, Migrate):
            migration_record = outcome["migration"]
        elif isinstance(intent, Transform) and migration_record is not None:
            cycles_after_migration.append(outcome)
        if outcome.get("stopped"):
            break

    record = {
        "schema": CONTROLLER_SCHEMA,
        "world": here.record(),
        "steps": steps,
        "final_generation": genesis.state["generation"],
        "final_components": lineage_state.component_names(genesis.state),
        "final_vocabulary": lineage_state.vocabulary_names(genesis.state),
        "causal_chain": genesis.causal_chain(),
        "budget": genesis.budget.record(),
        "mechanism_execution_isolated": True,
        "mechanism_artifact_digest": "" if mechanism_artifact is None else str(mechanism_artifact.get("artifact_digest") or ""),
    }
    if migration_record is not None:
        record["metamorphosis"] = metamorphosis_succeeded(migration_record, cycles_after_migration)
    record["run_digest"] = digest_of(record)
    return record


def _lineage(genesis: Genesis) -> dict[str, Any]:
    return {
        "generation": genesis.state["generation"],
        "components": lineage_state.component_names(genesis.state),
        "vocabulary": lineage_state.vocabulary_names(genesis.state),
        "acquisitions": len(genesis.state["acquisitions"]),
        "observations_kept": len(genesis.state["observations"]),
        "state_digest": genesis.state["state_digest"],
    }


def _summary(intent: Any, outcome: Mapping[str, Any]) -> dict[str, Any]:
    if isinstance(intent, Transform):
        return {
            "name": intent.name,
            "accepted": outcome.get("accepted"),
            "reason": outcome.get("reason", ""),
            "outcomes_are_self_reported": outcome.get("outcomes_are_self_reported"),
            "causal_dependency": outcome.get("causal_dependency"),
            "stopped": outcome.get("stopped", False),
        }
    return {k: v for k, v in outcome.items() if k not in ("migration", "diagnosis")}
