"""Apply an acquired Genesis v2 transformation-language extension through ordinary machinery.

The extension-search controller deliberately stops after acquiring a wider transformation language.
Its winning policy/body pair is evidence of reach, not permission to install either artifact.  This
module performs the next transaction:

* reconstruct the exact predecessor transformation language from lineage history;
* prove the selected policy descendant is outside that predecessor language's complete held-operator
  image;
* revalidate the exact resolving program on the current objective under the unchanged trust root;
* install only the search-policy descendant generated by the acquired operator;
* let that policy run normally until the ordinary controller accepts or exhausts its candidates; and
* retain a causal language -> policy -> body record that survives process death.

The counterfactual here is intentionally structural and executable: removing the newly acquired
operator from the language makes the exact policy descendant unconstructible by every operator the
predecessor held.  The body is still adopted only by the ordinary sandbox/trust-root path.  This is
first-generation DEVELOPMENT evidence toward Genesis v2, not the recursive second extension required
by the Open Metamorphosis stopping criterion.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

from genesis import controller, objective_policy_controller as opc
from genesis import policies, policy_body_lineage, policy_controller, programs
from genesis import retentive_objectives as retentive
from genesis import state as lineage_state
from genesis import transformation_language as language
from genesis import transformation_language_controller as language_controller
from genesis.loop import evaluation_snapshot
from genesis.sandbox import run_candidate
from genesis.trust_root import (
    BudgetExhausted,
    TrustRootError,
    artifact_digest_of,
    decide,
    digest_of,
    provenance,
    verify_verdict,
)

APPLICATION_SCHEMA = "genesis-transformation-language-application-v1"
POLICY_CERTIFICATE_SCHEMA = "genesis-transformation-language-policy-certificate-v1"
CAUSAL_RECORD_SCHEMA = "genesis-transformation-language-causal-chain-v1"
POLICY_UPDATE_ARM = "transformation_language_generated_search_policy_update"


class TransformationLanguageApplicationError(RuntimeError):
    """Raised when an acquired language cannot justify the machinery/body transition it enables."""


def _extension_observations(genesis) -> tuple[dict[str, Any], ...]:
    values = []
    for item in genesis.state.get("observations", []):
        if not isinstance(item, Mapping) or item.get("kind") != "transformation_language_extension":
            continue
        certificate = item.get("certificate")
        if isinstance(certificate, Mapping):
            values.append(dict(certificate))
    return tuple(values)


def _extension_for_digest(genesis, language_digest: str) -> dict[str, Any] | None:
    matches = [
        item
        for item in _extension_observations(genesis)
        if item.get("descendant_language_digest") == language_digest
    ]
    if not matches:
        return None
    if len(matches) != 1:
        raise TransformationLanguageApplicationError(
            "lineage history contains more than one extension certificate for one language digest"
        )
    return matches[0]


def _reconstruct_parent_language(genesis, current, certificate) -> dict[str, Any]:
    """Reconstruct the exact immediate predecessor from the append-only extension history."""
    held = language.validate_language(current)
    selected = language.validate_operator(certificate.get("operator") or {})
    prior_digest = str(certificate.get("prior_language_digest") or "")
    if not prior_digest:
        raise TransformationLanguageApplicationError("language extension certificate names no parent")
    if held.get("parent_language_digest") != prior_digest:
        raise TransformationLanguageApplicationError(
            "held language does not name the extension certificate's parent"
        )

    remaining = [
        item for item in held["operators"] if item["operator_digest"] != selected["operator_digest"]
    ]
    if len(remaining) != len(held["operators"]) - 1:
        raise TransformationLanguageApplicationError(
            "selected extension operator is not present exactly once in the held language"
        )

    parent_extension = _extension_for_digest(genesis, prior_digest)
    parent_parent_digest = (
        "" if parent_extension is None else str(parent_extension.get("prior_language_digest") or "")
    )
    predecessor = language.create_language(
        remaining,
        max_operator_steps=int(held["max_operator_steps"]),
        parent_language_digest=parent_parent_digest,
    )
    if predecessor["language_digest"] != prior_digest:
        raise TransformationLanguageApplicationError(
            "the predecessor language cannot be reconstructed from retained lineage history"
        )
    return predecessor


def _policy_image(language_artifact, prior_policy) -> tuple[dict[str, Any], ...]:
    """Complete one-operator policy image of a held transformation language."""
    held = language.validate_language(language_artifact)
    prior = policies.validate(prior_policy)
    image: list[dict[str, Any]] = []
    for operator in held["operators"]:
        try:
            candidate = language.apply_operator(prior, held, operator["name"])
        except language.TransformationLanguageError as problem:
            image.append(
                {
                    "operator_digest": operator["operator_digest"],
                    "policy_digest": "",
                    "constructible": False,
                    "reason": str(problem),
                }
            )
            continue
        image.append(
            {
                "operator_digest": operator["operator_digest"],
                "policy_digest": candidate["policy_digest"],
                "constructible": True,
                "reason": "",
            }
        )
    return tuple(image)


def _spend_application_evaluation(genesis) -> None:
    try:
        genesis.budget.spend("language_application_evaluations")
    except (TrustRootError, BudgetExhausted) as problem:
        raise TransformationLanguageApplicationError(
            "language application needs one prospectively admitted "
            "'language_application_evaluations' budget unit: %s" % problem
        ) from problem


def _revalidate_witness(genesis, here, *, candidate_policy, operator, certificate):
    witness = certificate.get("witness") or {}
    operations = tuple(str(name) for name in witness.get("operations") or [])
    if not operations:
        raise TransformationLanguageApplicationError(
            "language extension certificate carries no resolving program"
        )
    if operations not in policies.candidate_sequences(candidate_policy):
        raise TransformationLanguageApplicationError(
            "language extension witness is not constructible by the policy it allegedly enabled"
        )

    _spend_application_evaluation(genesis)
    questions = evaluation_snapshot(here.tasks)
    parent = run_candidate(
        genesis.body_factory,
        questions,
        genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
        grade=genesis.grade,
    )
    if not parent["completed"]:
        raise TransformationLanguageApplicationError(
            "current body could not be remeasured before language application"
        )
    generated = programs.artifact(
        registry_reference=candidate_policy["registry_reference"],
        operations=operations,
        input_field=candidate_policy["input_field"],
    )
    body_artifact = artifact_digest_of(generated)
    candidate = run_candidate(
        generated,
        questions,
        genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
        grade=genesis.grade,
    )
    if not candidate["completed"]:
        raise TransformationLanguageApplicationError(
            "language extension resolving program could not be remeasured"
        )
    verdict = decide(
        parent_outcomes=parent["outcomes"],
        candidate_outcomes=candidate["outcomes"],
        budget=genesis.budget,
        isolation=genesis.isolation,
        admitted_isolation=genesis.admitted_isolation,
        candidate_provenance=provenance(
            "lineage_owned",
            produced_by="Genesis v2 acquired transformation-language application",
            detail=operator["operator_digest"],
        ),
        evaluation_contract_record=genesis.evaluation_contract,
    )
    problems = verify_verdict(verdict, admitted_source_sha256=genesis.admitted_source_sha256)
    if problems:
        raise TransformationLanguageApplicationError("; ".join(problems))
    if not verdict.get("accepted"):
        raise TransformationLanguageApplicationError(
            "acquired language's resolving program no longer passes the unchanged trust root"
        )
    return {
        "operations": list(operations),
        "body_artifact": body_artifact,
        "sandbox_digest": candidate["result_digest"],
        "verdict_digest": verdict["verdict_digest"],
        "candidate_solved": int(verdict["candidate"]["counts"]["solved"]),
        "parent_solved": int(verdict["parent"]["counts"]["solved"]),
    }


def _install_policy(genesis, *, objective, prior_policy, candidate_policy, current_language, parent_language, certificate, operator, predecessor_image, revalidation):
    if candidate_policy["parent_policy_digest"] != prior_policy["policy_digest"]:
        raise TransformationLanguageApplicationError(
            "acquired operator did not construct a direct descendant of the held search policy"
        )
    predecessor_digests = {
        item["policy_digest"] for item in predecessor_image if item.get("constructible")
    }
    if candidate_policy["policy_digest"] in predecessor_digests:
        raise TransformationLanguageApplicationError(
            "candidate policy was already constructible by the predecessor transformation language"
        )

    payload = {
        "schema": POLICY_CERTIFICATE_SCHEMA,
        "objective": objective,
        "prior_language_digest": parent_language["language_digest"],
        "acquired_language_digest": current_language["language_digest"],
        "language_extension_certificate_digest": str(certificate.get("certificate_digest") or ""),
        "operator": operator,
        "prior_policy_digest": prior_policy["policy_digest"],
        "new_policy_digest": candidate_policy["policy_digest"],
        "predecessor_policy_image": list(predecessor_image),
        "candidate_policy_outside_predecessor_image": True,
        "resolving_program": revalidation,
        "evaluation_contract_digest": genesis.evaluation_contract["contract_digest"],
        "trust_root_source_sha256": genesis.admitted_source_sha256,
        "causal_dependency": {
            "established": True,
            "kind": "transformation_language_operator_availability",
            "counterfactual": "remove the acquired operator and reconstruct the exact predecessor language",
            "candidate_policy_constructible_without_extension": False,
        },
    }
    policy_certificate = {**payload, "certificate_digest": digest_of(payload)}
    observation = {
        "kind": "search_policy_updated",
        "update_kind": "transformation_language_operator_application",
        "objective_digest": objective["objective_digest"],
        "prior_policy_digest": prior_policy["policy_digest"],
        "new_policy_digest": candidate_policy["policy_digest"],
        "language_digest": current_language["language_digest"],
        "operator_digest": operator["operator_digest"],
        "certificate_digest": policy_certificate["certificate_digest"],
        "causal_dependency": policy_certificate["causal_dependency"],
    }
    policy_controller._replace_or_add_policy(
        genesis,
        candidate_policy,
        provenance_record=provenance(
            "lineage_owned",
            produced_by="Genesis v2 acquired transformation-language operator",
            detail=policy_certificate["certificate_digest"],
        ),
        observation=observation,
    )
    entry = genesis.journal.append(
        "observation",
        genesis.state["generation"],
        {
            "arm": POLICY_UPDATE_ARM,
            "certificate": policy_certificate,
            "new_state_digest": genesis.state["state_digest"],
        },
    )
    return policy_certificate, entry


def apply_acquired_extension(
    genesis,
    here,
    *,
    max_policy_steps: int = 32,
    checkpoint_directory: Path | None = None,
) -> dict[str, Any]:
    """Use the most recent acquired language operator, then let ordinary policy search adopt a body."""
    retentive.assert_retains_prior_work(genesis, here)
    prior_policy = policy_controller.bound_policy(genesis)
    if prior_policy is None:
        raise TransformationLanguageApplicationError("lineage has no search policy to transform")
    if not opc.exhausted(genesis, here, prior_policy):
        raise TransformationLanguageApplicationError(
            "held body-search policy is not exhausted on this objective"
        )

    current_language = language_controller.bound_language(genesis)
    if current_language is None:
        raise TransformationLanguageApplicationError("lineage has no transformation language")
    extension = _extension_for_digest(genesis, current_language["language_digest"])
    if extension is None:
        raise TransformationLanguageApplicationError(
            "current transformation language is only host-admitted; no acquired extension exists"
        )
    if extension.get("prior_policy_digest") != prior_policy["policy_digest"]:
        raise TransformationLanguageApplicationError(
            "current search policy is not the one whose exhaustion licensed this language extension"
        )

    parent_language = _reconstruct_parent_language(genesis, current_language, extension)
    operator = language.validate_operator(extension.get("operator") or {})
    candidate_policy = language.apply_operator(prior_policy, current_language, operator["name"])
    expected_policy_digest = str(extension.get("candidate_policy_digest") or "")
    if candidate_policy["policy_digest"] != expected_policy_digest:
        raise TransformationLanguageApplicationError(
            "acquired operator no longer reconstructs the policy measured during language selection"
        )

    predecessor_image = _policy_image(parent_language, prior_policy)
    objective = opc.objective_record(genesis, here)
    revalidation = _revalidate_witness(
        genesis,
        here,
        candidate_policy=candidate_policy,
        operator=operator,
        certificate=extension,
    )
    policy_certificate, policy_entry = _install_policy(
        genesis,
        objective=objective,
        prior_policy=prior_policy,
        candidate_policy=candidate_policy,
        current_language=current_language,
        parent_language=parent_language,
        certificate=extension,
        operator=operator,
        predecessor_image=predecessor_image,
        revalidation=revalidation,
    )

    checkpoint_path = Path(checkpoint_directory) if checkpoint_directory is not None else None
    policy_checkpoint = ""
    if checkpoint_path is not None:
        policy_checkpoint = genesis.persist(checkpoint_path)["checkpoint"]

    # Do not install the meta-evaluation witness.  Run the changed policy through the same ordinary
    # objective-scoped controller path as any other lineage-held search machinery.
    body_steps: list[dict[str, Any]] = []
    adopted = None
    for _ in range(max_policy_steps):
        current_policy = policy_controller.bound_policy(genesis)
        if current_policy is None or current_policy["policy_digest"] != candidate_policy["policy_digest"]:
            raise TransformationLanguageApplicationError(
                "search policy changed outside the acquired-language application transaction"
            )
        intent = opc._invoke_policy(genesis, current_policy, objective)
        if intent is None or isinstance(intent, controller.Stop):
            body_steps.append(
                {
                    "intent": "stop",
                    "reason": getattr(intent, "reason", "no policy intent"),
                }
            )
            break
        if not isinstance(intent, controller.GenerateTransform):
            raise TransformationLanguageApplicationError(
                "changed policy emitted an intent outside generated-body search"
            )
        rationale = dict(intent.rationale or {})
        if rationale.get("search_policy_digest") != candidate_policy["policy_digest"]:
            raise TransformationLanguageApplicationError(
                "generated body intent names machinery other than the acquired-language policy"
            )
        if rationale.get("search_objective_digest") != objective["objective_digest"]:
            raise TransformationLanguageApplicationError(
                "generated body intent names a different objective"
            )
        outcome = controller._generate_transform(genesis, here, intent)
        step = {
            "intent": "GenerateTransform",
            "name": intent.name,
            "program": outcome["generated_program"],
            "body_artifact": outcome["generated_body_artifact"],
            "accepted": bool(outcome.get("accepted")),
            "reason": outcome.get("reason", ""),
        }
        body_steps.append(step)
        if outcome.get("accepted"):
            link = policy_body_lineage.record_adoption(
                genesis,
                objective=objective,
                policy=candidate_policy,
                intent=intent,
                outcome=outcome,
            )
            corpus = retentive._install_corpus(genesis, here, intent.name)
            step["policy_body_link"] = link
            step["retention_corpus_digest"] = corpus["corpus_digest"]
            adopted = {
                "name": intent.name,
                "program": outcome["generated_program"],
                "body_artifact": outcome["generated_body_artifact"],
                "verdict_digest": outcome["verdict"]["verdict_digest"],
                "policy_body_link_digest": link["link_digest"],
            }
            break
        if outcome.get("stopped"):
            break

    if adopted is None:
        raise TransformationLanguageApplicationError(
            "acquired transformation language changed machinery but ordinary policy execution "
            "did not adopt a body within the admitted execution bound"
        )

    causal_payload = {
        "schema": CAUSAL_RECORD_SCHEMA,
        "objective_digest": objective["objective_digest"],
        "prior_language_digest": parent_language["language_digest"],
        "acquired_language_digest": current_language["language_digest"],
        "operator_digest": operator["operator_digest"],
        "prior_policy_digest": prior_policy["policy_digest"],
        "new_policy_digest": candidate_policy["policy_digest"],
        "policy_certificate_digest": policy_certificate["certificate_digest"],
        "policy_body_link_digest": adopted["policy_body_link_digest"],
        "adopted_body": adopted,
        "language_ablation": {
            "established": True,
            "predecessor_complete_operator_image_measured": True,
            "candidate_policy_in_predecessor_image": False,
            "removed_operator_digest": operator["operator_digest"],
        },
        "trust_root_source_sha256": genesis.admitted_source_sha256,
        "evaluation_contract_digest": genesis.evaluation_contract["contract_digest"],
    }
    causal_record = {**causal_payload, "causal_digest": digest_of(causal_payload)}
    genesis.state = lineage_state.create_state(
        body_digest=genesis.state["body_digest"],
        components=genesis.state["components"],
        vocabulary=genesis.state["vocabulary"],
        tools=genesis.state["tools"],
        acquisitions=genesis.state["acquisitions"],
        observations=genesis.state["observations"] + [causal_record],
        generation=genesis.state["generation"],
    )
    causal_entry = genesis.journal.append(
        "observation",
        genesis.state["generation"],
        {
            "arm": "transformation_language_causal_application",
            "causal_record": causal_record,
            "new_state_digest": genesis.state["state_digest"],
        },
    )
    final_checkpoint = ""
    if checkpoint_path is not None:
        final_checkpoint = genesis.persist(checkpoint_path)["checkpoint"]

    result = {
        "schema": APPLICATION_SCHEMA,
        "objective": objective,
        "prior_language": parent_language,
        "current_language": current_language,
        "operator": operator,
        "prior_policy": prior_policy,
        "new_policy": candidate_policy,
        "predecessor_policy_image": list(predecessor_image),
        "policy_revalidation": revalidation,
        "policy_certificate": policy_certificate,
        "policy_journal_entry": policy_entry["entry_digest"],
        "policy_checkpoint_digest": policy_checkpoint,
        "body_steps": body_steps,
        "body_adopted": True,
        "causal_record": causal_record,
        "causal_journal_entry": causal_entry["entry_digest"],
        "final_checkpoint_digest": final_checkpoint,
        "final_state_digest": genesis.state["state_digest"],
    }
    result["application_digest"] = digest_of(result)
    return result
